- name: Setup Azure devops virtual machine
  hosts: localhost
  connection: local

  vars:
    - resource_group_name: rg-caf-devops-maintainer-01
    - location: southeastasia
    - vnet_name: vnet-caf-devops
    - address_prefixes: "192.168.111.0/24"
    - vm_name: caf-devops-01
    - admin_username: king.admin
    - vm_size: Standard_F8s_v2
    - auto_shutdown_utc: 1600
    - key_name: "{{vm_name}}"

  tasks:
    - debug:
        msg: "{{wsl_profile_path}}"

    - name: Generate SSH key
      include_tasks: ./modules/ssh_key/ansible.yaml
      loop_control:
        loop_var: item_path
      loop:
        - "{{wsl_profile_path}}/.ssh/{{key_name}}"
      vars:
        copy_to_home_folder: true
        


    - name: Get public ip address
      shell: dig +short myip.opendns.com @resolver1.opendns.com
      register: pip

    - debug:
        msg: "{{pip.stdout}}/32"

    - name: Create resource group
      azure_rm_resourcegroup:
        name: "{{ resource_group_name }}"
        location: "{{ location }}"

    - name: Create virtual network
      azure_rm_virtualnetwork:
        resource_group: "{{ resource_group_name }}"
        name: "{{ vnet_name }}"
        address_prefixes: "192.168.111.0/24"

    - name: Add devops-vm subnet
      azure_rm_subnet:
        resource_group: "{{ resource_group_name }}"
        name: devops-vm
        address_prefix: "192.168.111.0/25"
        virtual_network: "{{ vnet_name }}"

    - name: Create Network Security Group
      azure_rm_securitygroup:
        resource_group: "{{ resource_group_name }}"
        name: nsg-remote-management
        rules:
          - name: 'ssh'
            protocol: Tcp
            destination_port_range: 22
            access: Allow
            priority: 501
            direction: Inbound
            source_address_prefix:
              - '{{pip.stdout}}/32'


    - name: Create public IP address
      azure_rm_publicipaddress:
        resource_group: "{{ resource_group_name }}"
        allocation_method: Static
        domain_name: "{{ vm_name }}"
        name: "{{ vm_name }}-pip-01"

    - name: Create a network interface
      azure_rm_networkinterface:
        name: "{{ vm_name }}-nic-01"
        resource_group: "{{ resource_group_name }}"
        virtual_network: "{{ vnet_name }}"
        subnet_name: devops-vm
        security_group: nsg-remote-management
        ip_configurations:
          - name: default
            public_ip_address_name: "{{ vm_name }}-pip-01"
            primary: True

    - name: Create VM
      azure_rm_virtualmachine:
        resource_group: "{{ resource_group_name }}"
        name: "{{ vm_name }}"
        vm_size: "{{ vm_size }}"
        os_disk_size_gb: 128
        admin_username: "{{ admin_username }}"
        network_interfaces: "{{ vm_name }}-nic-01"
        os_type: Linux
        managed_disk_type: Premium_LRS
        vm_identity: SystemAssigned
        ssh_password_enabled: false
        ssh_public_keys: 
          - path: "/home/{{ admin_username }}/.ssh/authorized_keys"
            key_data: "{{key_content.stdout}}"
        image:
          offer: 0001-com-ubuntu-server-focal
          publisher: canonical
          sku: 20_04-lts-gen2
          version: latest

    # Time is UTC
    - name: Enable auto-shutdown at {{ auto_shutdown_utc }} UTC
      shell: "az vm auto-shutdown -g {{ resource_group_name }} -n {{ vm_name }} --time {{ auto_shutdown_utc }}"

    - name: Get facts for one Public IP
      azure_rm_publicipaddress_info:
        resource_group: "{{ resource_group_name }}"
        name: "{{ vm_name }}-pip-01"
      register: publicipaddresses

    - name: register facts
      set_fact: 
        fqdn: "{{ publicipaddresses | json_query('publicipaddresses[0].dns_settings.fqdn')}}"
        admin_username: "{{ admin_username }}"
      register: vm

    - name: wait for the ssh port to come online
      wait_for:
        port: 22
        host: '{{ vm.ansible_facts.fqdn }}'
        timeout: 600

    # Update Host path on Windows user profile and in the ubuntu vm
    - name: Update ssh config and known_hosts file
      include_tasks: ./modules/known_hosts/ansible.yaml
      loop_control:
        loop_var: item_path
      loop:
        - "{{wsl_profile_path}}"
        - "~"

    - debug:
        msg: "{{vm}}"

    - name: Add a host with a non-standard port local to your machines
      add_host:
        name: '{{ vm.ansible_facts.fqdn }}'
        ansible_user: "{{ admin_username }}"
        groups: devops

- name: Setup the CAF development tools
  hosts: devops
  gather_facts: true
  become: true

  tasks:
    - name: Setup remote deployment VM
      include_tasks: ./modules/rover_deployment_vm/ansible.yaml
